// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_water_master = "CgkIs5fM2c8dEAIQAg"; // <GPGSID>
        public const string achievement_earth_master = "CgkIs5fM2c8dEAIQAQ"; // <GPGSID>
        public const string achievement_power = "CgkIs5fM2c8dEAIQBw"; // <GPGSID>
        public const string achievement_oh_hello = "CgkIs5fM2c8dEAIQAA"; // <GPGSID>
        public const string achievement_the_alchemist = "CgkIs5fM2c8dEAIQBg"; // <GPGSID>
        public const string achievement_might = "CgkIs5fM2c8dEAIQCA"; // <GPGSID>
        public const string achievement_blade_master = "CgkIs5fM2c8dEAIQBQ"; // <GPGSID>
        public const string achievement_air_master = "CgkIs5fM2c8dEAIQBA"; // <GPGSID>
        public const string achievement_curiosity = "CgkIs5fM2c8dEAIQEA"; // <GPGSID>
        public const string achievement_the_glutton = "CgkIs5fM2c8dEAIQDw"; // <GPGSID>
        public const string achievement_greed = "CgkIs5fM2c8dEAIQCQ"; // <GPGSID>
        public const string achievement_knowledge = "CgkIs5fM2c8dEAIQDQ"; // <GPGSID>
        public const string achievement_fire_master = "CgkIs5fM2c8dEAIQAw"; // <GPGSID>
        public const string achievement_the_end = "CgkIs5fM2c8dEAIQDA"; // <GPGSID>
        public const string achievement_traveler = "CgkIs5fM2c8dEAIQCw"; // <GPGSID>
        public const string achievement_bestiary = "CgkIs5fM2c8dEAIQCg"; // <GPGSID>

}

